controller_manager:
  ros__parameters:
    update_rate: 50

    hardware_components_initial_state:
      inactive:
        - ThrustersSystem

    thruster_test_controller:
      type: forward_command_controller/ForwardCommandController

    body_force_controller:
      type: cirtesub_controllers/BodyForceController
    
    body_velocity_controller:
      type: cirtesub_controllers/BodyVelocityController

    stabilize_controller:
      type: cirtesub_controllers/StabilizeController

thruster_test_controller:
  ros__parameters:
    joints:
      - cirtesub/Thruster_up_front
      - cirtesub/Thruster_up_back
      - cirtesub/Thruster_up_left
      - cirtesub/Thruster_up_right
      - cirtesub/Thruster_down_backleft
      - cirtesub/Thruster_down_backright
      - cirtesub/Thruster_down_frontleft
      - cirtesub/Thruster_down_frontright
    interface_name: effort

body_force_controller:
  ros__parameters:
    input_topic: /body_force/command

body_velocity_controller:
  ros__parameters:
    cmd_vel_topic: /cmd_vel
    navigator_topic: /navigator_msg
    body_force_controller_name: body_force_controller

    kp_u: 4000.0
    ki_u: 40.0
    kd_u: 5.0

    kp_r: 3000.0
    ki_r: 10.0
    kd_r: 10.0

stabilize_controller:
  ros__parameters:
    feedforward_topic: stabilize_controller/feedforward
    navigator_topic: /cirtesub/navigator/navigation
    debug_wrench_topic: /stabilize_controller/debug_wrench
    body_force_controller_name: body_force_controller

    kp_roll: 15.0
    ki_roll: 3.0
    kd_roll: 5.0

    kp_pitch: 15.0
    ki_pitch: 3.0
    kd_pitch: 5.0

    kp_yaw: 10.0
    ki_yaw: 2.0
    kd_yaw: 6.0

    yaw_command_threshold: 0.001
