controller_manager:
  ros__parameters:
    update_rate: 50

    hardware_components_initial_state:
      inactive:
        - cirtesub_thrusters

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    thruster_test_controller:
      type: forward_command_controller/ForwardCommandController

    body_force_controller:
      type: cirtesub_controllers/BodyForceController

    body_velocity_controller:
      type: cirtesub_controllers/BodyVelocityController

    position_hold_controller:
      type: cirtesub_controllers/PositionHoldController

    stabilize_controller:
      type: cirtesub_controllers/StabilizeController

    depth_hold_controller:
      type: cirtesub_controllers/DepthHoldController

    alpha_left_forward_velocity_controller:
      type: forward_command_controller/ForwardCommandController

    alpha_right_forward_velocity_controller:
      type: forward_command_controller/ForwardCommandController

    alpha_left_joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    alpha_right_joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    task_priority_controller:
      type: task_priority_kinematic_control/TaskPriorityController

thruster_test_controller:
  ros__parameters:
    joints:
      - cirtesub/Thruster_up_front
      - cirtesub/Thruster_up_back
      - cirtesub/Thruster_up_left
      - cirtesub/Thruster_up_right
      - cirtesub/Thruster_down_backleft
      - cirtesub/Thruster_down_backright
      - cirtesub/Thruster_down_frontleft
      - cirtesub/Thruster_down_frontright
    interface_name: effort

body_force_controller:
  ros__parameters:
    input_topic: /body_force/command
    debug.enabled: false

body_velocity_controller:
  ros__parameters:
    debug.enabled: false
    setpoint_topic: /body_velocity_controller/setpoint
    navigator_topic: /cirtesub/navigator/navigation
    feedforward_topic: /depth_hold_controller/feedforward
    body_force_controller_name: body_force_controller

    kp_x: 100.0
    ki_x: 50.0
    kd_x: 0.0
    antiwindup_x: 10.0

    kp_y: 100.0
    ki_y: 50.0
    kd_y: 0.0
    antiwindup_y: 10.0

    kp_z: 800.0
    ki_z: 400.0
    kd_z: 0.0
    antiwindup_z: 10.0

    kp_roll: 100.0
    ki_roll: 50.0
    kd_roll: 0.0
    antiwindup_roll: 10.0

    kp_pitch: 100.0
    ki_pitch: 50.0
    kd_pitch: 0.0
    antiwindup_pitch: 10.0

    kp_yaw: 15.0
    ki_yaw: 8.0
    kd_yaw: 0.0
    antiwindup_yaw: 10.0

position_hold_controller:
  ros__parameters:
    debug.enabled: false
    setpoint_topic: /position_hold_controller/setpoint
    feedforward_topic: /position_hold_controller/feedforward
    navigator_topic: /cirtesub/navigator/navigation
    body_velocity_controller_name: body_velocity_controller
    setpoint_frame_id: world_ned

    kp_x: 1.0
    ki_x: 0.0
    kd_x: 0.0
    antiwindup_x: 1.0

    kp_y: 1.0
    ki_y: 0.0
    kd_y: 0.0
    antiwindup_y: 1.0

    kp_z: 1.0
    ki_z: 0.0
    kd_z: 0.0
    antiwindup_z: 1.0

    kp_roll: 1.0
    ki_roll: 0.0
    kd_roll: 0.0
    antiwindup_roll: 1.0

    kp_pitch: 1.0
    ki_pitch: 0.0
    kd_pitch: 0.0
    antiwindup_pitch: 1.0

    kp_yaw: 1.0
    ki_yaw: 0.0
    kd_yaw: 0.0
    antiwindup_yaw: 1.0

    linear_feedforward_threshold: 0.001
    angular_feedforward_threshold: 0.001
    feedforward_timeout: 0.25

stabilize_controller:
  ros__parameters:
    debug.enabled: false
    feedforward_topic: /stabilize_controller/feedforward
    navigator_topic: /cirtesub/navigator/navigation
    body_force_controller_name: body_force_controller
    enable_roll_pitch_service_name: /stabilize_controller/enable_roll_pitch
    disable_roll_pitch_service_name: /stabilize_controller/disable_roll_pitch
    allow_roll_pitch: false
    feedforward_gain_x: 1.0
    feedforward_gain_y: 1.0
    feedforward_gain_z: 1.0
    feedforward_gain_roll: 1.0
    feedforward_gain_pitch: 1.0
    feedforward_gain_yaw: 1.0

    kp_roll: 50.0
    ki_roll: 40.0
    kd_roll: 40.0
    antiwindup_roll: 10.0

    kp_pitch: 50.0
    ki_pitch: 40.0
    kd_pitch: 40.0
    antiwindup_pitch: 10.0

    kp_yaw: 10.0
    ki_yaw: 2.0
    kd_yaw: 6.0
    antiwindup_yaw: 10.0

    yaw_command_threshold: 0.001
    roll_command_threshold: 0.001
    pitch_command_threshold: 0.001

depth_hold_controller:
  ros__parameters:
    debug.enabled: false
    feedforward_topic: /depth_hold_controller/feedforward
    navigator_topic: /cirtesub/navigator/navigation
    setpoint_topic: /depth_hold_controller/set_point
    body_force_controller_name: body_force_controller
    enable_roll_pitch_service_name: /depth_hold_controller/enable_roll_pitch
    disable_roll_pitch_service_name: /depth_hold_controller/disable_roll_pitch
    allow_roll_pitch: false
    feedforward_gain_x: 1.0
    feedforward_gain_y: 1.0
    feedforward_gain_z: 1.0
    feedforward_gain_roll: 1.0
    feedforward_gain_pitch: 1.0
    feedforward_gain_yaw: 1.0

    kp_roll: 50.0
    ki_roll: 40.0
    kd_roll: 40.0
    antiwindup_roll: 10.0

    kp_pitch: 50.0
    ki_pitch: 40.0
    kd_pitch: 40.0
    antiwindup_pitch: 10.0

    kp_yaw: 10.0
    ki_yaw: 2.0
    kd_yaw: 6.0
    antiwindup_yaw: 10.0

    kp_depth: 400.0
    ki_depth: 100.0
    kd_depth: 400.0
    antiwindup_depth: 10.0

    command_threshold: 0.001
    depth_command_threshold: 0.001

alpha_left_forward_velocity_controller:
  ros__parameters:
    joints:
      - cirtesub/alpha_left/axis_a
      - cirtesub/alpha_left/axis_b
      - cirtesub/alpha_left/axis_c
      - cirtesub/alpha_left/axis_d
      - cirtesub/alpha_left/axis_e
    interface_name: velocity

alpha_right_forward_velocity_controller:
  ros__parameters:
    joints:
      - cirtesub/alpha_right/axis_a
      - cirtesub/alpha_right/axis_b
      - cirtesub/alpha_right/axis_c
      - cirtesub/alpha_right/axis_d
      - cirtesub/alpha_right/axis_e
    interface_name: velocity

alpha_left_joint_trajectory_controller:
  ros__parameters:
    joints:
      - cirtesub/alpha_left/axis_a
      - cirtesub/alpha_left/axis_b
      - cirtesub/alpha_left/axis_c
      - cirtesub/alpha_left/axis_d
      - cirtesub/alpha_left/axis_e
    command_interfaces:
      - velocity
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 40.0
    command_publish_rate: 40.0
    allow_nonzero_velocity_at_trajectory_end: false
    interpolation_method: splines
    gains:
      cirtesub/alpha_left/axis_a:
        p: 0.5
        i: 0.0
        d: 0.0
        i_clamp_min: -1.0
        i_clamp_max: 1.0
        ff_velocity_scale: 1.0
      cirtesub/alpha_left/axis_b:
        p: 0.5
        i: 0.0
        d: 0.0
        i_clamp_min: -1.0
        i_clamp_max: 1.0
        ff_velocity_scale: 1.0
      cirtesub/alpha_left/axis_c:
        p: 0.5
        i: 0.0
        d: 0.0
        i_clamp_min: -1.0
        i_clamp_max: 1.0
        ff_velocity_scale: 1.0
      cirtesub/alpha_left/axis_d:
        p: 0.5
        i: 0.0
        d: 0.0
        i_clamp_min: -1.0
        i_clamp_max: 1.0
        ff_velocity_scale: 1.0
      cirtesub/alpha_left/axis_e:
        p: 0.5
        i: 0.0
        d: 0.0
        i_clamp_min: -1.0
        i_clamp_max: 1.0
        ff_velocity_scale: 1.0

alpha_right_joint_trajectory_controller:
  ros__parameters:
    joints:
      - cirtesub/alpha_right/axis_a
      - cirtesub/alpha_right/axis_b
      - cirtesub/alpha_right/axis_c
      - cirtesub/alpha_right/axis_d
      - cirtesub/alpha_right/axis_e
    command_interfaces:
      - velocity
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 40.0
    command_publish_rate: 40.0
    allow_nonzero_velocity_at_trajectory_end: false
    interpolation_method: splines
    gains:
      cirtesub/alpha_right/axis_a:
        p: 0.5
        i: 0.0
        d: 0.0
        i_clamp_min: -1.0
        i_clamp_max: 1.0
        ff_velocity_scale: 1.0
      cirtesub/alpha_right/axis_b:
        p: 0.5
        i: 0.0
        d: 0.0
        i_clamp_min: -1.0
        i_clamp_max: 1.0
        ff_velocity_scale: 1.0
      cirtesub/alpha_right/axis_c:
        p: 0.5
        i: 0.0
        d: 0.0
        i_clamp_min: -1.0
        i_clamp_max: 1.0
        ff_velocity_scale: 1.0
      cirtesub/alpha_right/axis_d:
        p: 0.5
        i: 0.0
        d: 0.0
        i_clamp_min: -1.0
        i_clamp_max: 1.0
        ff_velocity_scale: 1.0
      cirtesub/alpha_right/axis_e:
        p: 0.5
        i: 0.0
        d: 0.0
        i_clamp_min: -1.0
        i_clamp_max: 1.0
        ff_velocity_scale: 1.0

task_priority_controller:
  ros__parameters:
    backend_plugin: task_priority_kinematic_control/KDLKinematicsBackend
    robot_description: ""
    robot_description_source_node: /robot_state_publisher_cirtesub
    robot_description_wait_timeout_sec: 5.0
    world_frame: world_ned
    base_frame: cirtesub/base_link
    left_tip_frame: cirtesub/alpha_left/standard_jaws_tool
    right_tip_frame: cirtesub/alpha_right/standard_jaws_tool
    left_arm_joints:
      - cirtesub/alpha_left/axis_a
      - cirtesub/alpha_left/axis_b
      - cirtesub/alpha_left/axis_c
      - cirtesub/alpha_left/axis_d
      - cirtesub/alpha_left/axis_e
    right_arm_joints:
      - cirtesub/alpha_right/axis_a
      - cirtesub/alpha_right/axis_b
      - cirtesub/alpha_right/axis_c
      - cirtesub/alpha_right/axis_d
      - cirtesub/alpha_right/axis_e
    active_base_dofs: [0, 1, 2, 3, 4, 5]
    solver_method: dls
    dls_lambda: 0.05
    dof_weights: [1.0, 1.0, 1.0, 2.0, 2.0, 1.0, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5]
    velocity_limits: [0.2, 0.2, 0.2, 0.3, 0.3, 0.3, 1.0, 1.0, 1.0, 1.0, 0.5, 1.0, 1.0, 1.0, 1.0, 0.5]
    navigator_topic: /cirtesub/navigator/navigation
    body_velocity_controller_name: body_velocity_controller
    left_arm_command_topic: /alpha_left_forward_velocity_controller/commands
    right_arm_command_topic: /alpha_right_forward_velocity_controller/commands

    task_ids:
      - base_pose
      - left_pose
      - right_pose
      - joint_limits
      - left_arm_nominal
      - right_arm_nominal
      - base_yaw

    tasks.base_pose.plugin: task_priority_kinematic_control/FramePoseTask
    tasks.base_pose.enabled: true
    tasks.base_pose.priority: 0.0
    tasks.base_pose.group: base
    tasks.base_pose.frame_id: cirtesub/base_link
    tasks.base_pose.gain: [1.0, 1.0, 1.0, 0.7, 0.7, 0.7]

    tasks.left_pose.plugin: task_priority_kinematic_control/FramePoseTask
    tasks.left_pose.enabled: true
    tasks.left_pose.priority: 1.0
    tasks.left_pose.group: left
    tasks.left_pose.frame_id: cirtesub/alpha_left/standard_jaws_tool
    tasks.left_pose.gain: [1.0, 1.0, 1.0, 0.7, 0.7, 0.7]

    tasks.right_pose.plugin: task_priority_kinematic_control/FramePoseTask
    tasks.right_pose.enabled: true
    tasks.right_pose.priority: 2.0
    tasks.right_pose.group: right
    tasks.right_pose.frame_id: cirtesub/alpha_right/standard_jaws_tool
    tasks.right_pose.gain: [1.0, 1.0, 1.0, 0.7, 0.7, 0.7]

    tasks.joint_limits.plugin: task_priority_kinematic_control/JointLimitsTask
    tasks.joint_limits.enabled: true
    tasks.joint_limits.priority: 3.0
    tasks.joint_limits.group: global
    tasks.joint_limits.margin: 0.1
    tasks.joint_limits.gain_scalar: 0.5
    tasks.joint_limits.lower_limits: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    tasks.joint_limits.upper_limits: [0.015, 3.22, 3.22, 3.49, 6.10, 0.015, 3.22, 3.22, 3.49, 6.10]

    tasks.left_arm_nominal.plugin: task_priority_kinematic_control/JointNominalTask
    tasks.left_arm_nominal.enabled: true
    tasks.left_arm_nominal.priority: 4.0
    tasks.left_arm_nominal.group: left
    tasks.left_arm_nominal.joint_names:
      - cirtesub/alpha_left/axis_a
      - cirtesub/alpha_left/axis_b
      - cirtesub/alpha_left/axis_c
      - cirtesub/alpha_left/axis_d
      - cirtesub/alpha_left/axis_e
    tasks.left_arm_nominal.target: [0.0, 1.2, 1.2, 1.0, 0.0]
    tasks.left_arm_nominal.gain: [0.2, 0.2, 0.2, 0.2, 0.2]

    tasks.right_arm_nominal.plugin: task_priority_kinematic_control/JointNominalTask
    tasks.right_arm_nominal.enabled: true
    tasks.right_arm_nominal.priority: 5.0
    tasks.right_arm_nominal.group: right
    tasks.right_arm_nominal.joint_names:
      - cirtesub/alpha_right/axis_a
      - cirtesub/alpha_right/axis_b
      - cirtesub/alpha_right/axis_c
      - cirtesub/alpha_right/axis_d
      - cirtesub/alpha_right/axis_e
    tasks.right_arm_nominal.target: [0.0, 1.2, 1.2, 1.0, 0.0]
    tasks.right_arm_nominal.gain: [0.2, 0.2, 0.2, 0.2, 0.2]

    tasks.base_yaw.plugin: task_priority_kinematic_control/BaseYawTask
    tasks.base_yaw.enabled: true
    tasks.base_yaw.priority: 6.0
    tasks.base_yaw.group: base
    tasks.base_yaw.target_yaw: 0.0
    tasks.base_yaw.gain_scalar: 0.5
